### ISSUE TITLE
Investigate the rollback caused by pullrequest.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#101] opened 2015-06-19 13:09 UTC
# Requirement
Change of the following PR # 6 has been removed by PR # 7.
- [Signal r chat #6](https://github.com/SymphonyTeleca/SampleProgram/pull/6)
- [Translate api #7](https://github.com/SymphonyTeleca/SampleProgram/pull/7)

Please investigate the conditions of occurrence of this problem.

**Comment by supragyan** [comment] 2015-07-28 06:09
@daisukenishino 

\>\>Change of the following PR # 6 has been removed by PR # 7.

In pull request 6, we have created SignalRChat feature branch .which contains only SignalRChat changes.

In pull request 7,simillarly we have created TranslateAPI feature branch ,which contains only Translate API changes.

But after pull request 7 merged we have recreated pull request 8 for SignalRChat branch which contains both SignalRChat and Translate API changes.

Regards,

**Comment by daisukenishino** [comment] 2015-07-28 06:47
@supragyan 

>But after pull request 7 merged we have recreated pull request 8 for SignalRChat branch which contains both SignalRChat and Translate API changes.

Is it the conclusion that the phenomenon of problem does not reproduce ?

**Comment by supragyan** [comment] 2015-07-29 06:51
Yes Nishino-San.

**Closed** 2015-08-25 06:17 UTC
Labels: question

**Comment by daisukenishino** [comment] 2015-11-02 05:36
@supragyan 

[If such a thing](https://github.com/OpenTouryoProject/OpenTouryo/issues/101#issuecomment-125860308), it is not a problem of pullrequest, 
there is a possibility that there were problems in the commit log.

I tried to investigate the commit log,
I found that modules of SignalR were disappeared at the following commit.

- Did code commit of Microsoft translate api sample application.  
https://github.com/SymphonyTeleca/SampleProgram/commit/73f8fa2ef812eb8d5a42708a54fbc12c5ff19be0
  - Deleted
    - ASPNET/SignalR/SignalRChat/README.md 
    - ASPNET/SignalR/SignalRChat.sln
    - ASPNET/SignalR/SignalRChat/SignalRChat.csproj 
    - ASPNET/SignalR/SignalRChat/Properties/AssemblyInfo.cs
    - ASPNET/SignalR/SignalRChat/Web.config
    - ASPNET/SignalR/SignalRChat/Startup.cs 
    - ASPNET/SignalR/SignalRChat/ChatHub.cs
    - ASPNET/SignalR/SignalRChat/Index.html
    - ASPNET/SignalR/SignalRChat/Scripts/・・・
    - ASPNET/SignalR/SignalRChat/・・・

**Comment by supragyan** [comment] 2015-11-02 07:33
@daisukenishino 
\>\>I tried to investigate the commit log,
\>\>I found that modules of SignalR were disappeared at the following commit.
Thank you for investigated the cause of this phenomenon.

We will also investigate the cause of deleted SignalR Chat files and let you know.

Regards,

**Comment by supragyan** [comment] 2015-11-02 10:20
@daisukenishino 
\>\>I found that modules of Signal R were disappeared at the following commit
\>\>https://github.com/SymphonyTeleca/SampleProgram/commit/73f8fa2ef812eb8d5a42708a54fbc12c5ff19be0 (pull request 7)
Yes the commit log is having problem because we deleted the signal r changes from Translate API feature branch and committed in pull request 7.

In pull request 8 we committed both signal r and Translate API changes but it has not merged.
So please reopen this pull request 8(https://github.com/SymphonyTeleca/SampleProgram/pull/8/) and merge if possible.

Is this OK or do we need to commit and create a new pull request for the Signal R changes again?

Please confirm.

**Comment by daisukenishino** [comment] 2015-11-04 02:04
@supragyan 

>So please reopen this [pull request 8](https://github.com/SymphonyTeleca/SampleProgram/pull/8/) and merge if possible.

I confirmed the [PR8](https://github.com/SymphonyTeleca/SampleProgram/pull/8/), and it had been pointed out problem.
And, you had sent a new [RP9](https://github.com/SymphonyTeleca/SampleProgram/pull/9/). I have already merged [RP9](https://github.com/SymphonyTeleca/SampleProgram/pull/9/).

**Comment by supragyan** [comment] 2015-11-12 12:51
@daisukenishino 
As pointed out the above comment, we have created new [pull request #10] (https://github.com/SymphonyTeleca/SampleProgram/pull/10) 
This pull request resolve the issue of missing packages and project related files.

We have tested and requested to merge [pull request #10] (https://github.com/SymphonyTeleca/SampleProgram/pull/10) .

Please confirm.

**Comment by daisukenishino** [comment] 2015-11-13 11:18
@supragyan 

Location of the discussion is not here.
