### ISSUE TITLE
I want to provide the following changes to VB version.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#105] opened 2015-07-13 13:59 UTC
# Requirement
I want to provide the following changes to VB version.

## (1)
- Changes to the JS file
- I've already merged.

## (2)
- Sample code of text change event on testScreen2.aspx ( + app.config).
- [I've already merged](https://github.com/OpenTouryoProject/OpenTouryo/pull/107).

## (3)
- jQGrid + WCF(JSON.NET)  
This is provided against edition of more than root_VS2010, because it require .NET v4.0.

## (4)
AsyncProcessingService :  
- Infrastructure.Business.AsyncProcessingService
- ~~ServiceInterface.AsyncProcessingService~~
- Sample.AsyncProcessingService

note : I aborted the VB migration of ServiceInterface.AsyncProcessingService.
Therefor, There is no need to migrate ServiceInterface.AsyncProcessingService to VB.

**Comment by supragyan** [comment] 2015-09-11 08:23
@daisukenishino 

\>\>I want to provide the following changes to VB version.

\>\>Sample code of text change event on testScreen2.aspx ( + app.config).

We have already completed this task and committed earlier.
We did check  it has been merged by daisukenishino to "/OpenTouryoProject/develop/"  branch as https://github.com/SymphonyTeleca/OpenTouryo/pull/55#event-363172599

Please let us know what is pending.

\>\>jQGrid + WCF(JSON.NET)

Do we need to commit the jQGrid + WCF(JSON.NET) in vb.net changes in all the root(root_VS2010, root_VS2012, root_VS2013) of "/Symphonyteleca/OpenTouryoTemplates/".
Because as we checked it seems "jQGrid + WCF(JSON.NET) in cs.net changes placed in all the root branches(root_VS2010, root_VS2012, root_VS2013) of ("/OpentouryoProject/OpenTouryoTemplates/")"

Please confirm

**Comment by daisukenishino** [comment] 2015-09-11 10:13
@supragyan 

>Please let us know what is pending.

- (1) and (2) tasks are already completed.
- (3) and (4) tasks are not completed.

>Please confirm

Please change the root_VS2010.

The task that reflect the changes of root_VS2010 to root_VS2012 & root_2013, it will perform at the "marge task". "[marge task](https://github.com/OpenTouryoProject/OpenTouryo/issues/104)" will be carried out at the end of the previous fiscal year.

**Comment by supragyan** [comment] 2015-09-11 10:40
@daisukenishino 
Thank you for confirmation.

\>\>(1) and (2) tasks are already completed.
Yes it is completed.

\>\>(3) and (4) tasks are not completed.
Task (4) is handling by Sandeep .
He will start this task after completed the 'Construction of VM document'.

In Task(3),
\>\>Please change the root_VS2010.
\>\>The task that reflect the changes of root_VS2010 to root_VS2012 & root_2013, it will perform at the "marge task". "marge task" will be carried out at the end of the previous fiscal year.

We will commit jQGrid + WCF(JSON.NET) changes to root_VS2010. of "/SymphonyTeleca/OpenTouryoTemplates/" 

Is this ok.
Please confirm.

**Comment by daisukenishino** [comment] 2015-09-11 10:57
@supragyan 

>Is this ok.

OK.
Changes of "/root_VS2010/programs/C#/" should be reflect to "/root_VS2010/programs/VB/".

**Comment by supragyan** [comment] 2015-09-11 11:03
@daisukenishino 

\>> Changes of "/root_VS2010/programs/C#/" should be reflect to "/root_VS2010/programs/VB/".

Thank you for the confirmation.
We will test and take care that it should be reflected as same as in the C#.

**Comment by SandeepNayak077** [comment] 2015-09-15 13:29
@daisukenishino 

We missed the following modification in the previous commit of (C#.Net)
- We missed to add AssemblyInfo file in the following project:
 - https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/AsyncSvc_sample/AsyncSvc_sample
 - https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/AsyncSvc_sample/TestAsyncSvc_Sample

- We missed to change the file name at following location:
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Business/MyApsBaseLogic.cs#L22

- We missed to add "((MyParameterValue)parameterValue).User" code for damAMT object at the following location:
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Business/Business/MyApsBaseLogic.cs#L334

We will commit the above modification while creating pull request of migration of VB.Net code.
Shall we commit above modification? 
Please confirm. 

Migration to VB.Net is completed.
We are in the process of review and testing.
We will deliver the changes by tomorrow (16-Sep-2015).

Please confirm.
 
Sorry for the inconvenience caused by the above code commit.
In future we will take care of it.

**Comment by daisukenishino** [comment] 2015-09-15 22:43
@supragyan 

>Shall we commit above modification?

Please send one pullrequest that collected these fixes.

>Migration to VB.Net is completed.

Do you also completed the (4) task?

**Comment by SandeepNayak077** [comment] 2015-09-16 05:38
@daisukenishino 

\>> Do you also completed the (4) task?

Yes, we have completed the migration process.
Internal code review and testing under process.
We will deliver it by today EOD.

**Closed** 2015-09-18 22:47 UTC
Labels: enhancement
