### ISSUE TITLE
We are currently merging.

### ISSUE THREAD

**Issue by daisukenishino** [OpenTouryoProject/OpenTouryo#104] opened 2015-07-06 03:34 UTC
# Requirement
Because it is in the [merge work](https://github.com/OpenTouryoProject/OpenTouryo/issues/38),
Please send as text without committing the modification for the following issues.

## Procedure of merging
- Performs the merge in the following order.  
root [new] -> root_easysetup -> root_VS2010 -> root_VS2012 -> root_VS2013.
- Confirm the difference between the edition of old version by using the Diff of WinMerge.
- Copy the new version to the old version location ( the old edition to the new edition location ).  
- Confirm the change of addition and deletion between the copy by using the Diff of WinMerge.
- Perform the additional work of the above-mentioned additional files by using the TortoiseGit.
- Commit the change of addition and deletion without update by using the TortoiseGit.
- Change of addition and deletion is confirmed by using the Diff of TortoiseGit's commit screen.  
( The difference between the edition, please note to the file other than the source file. )
- Commit the changes of the update by using the TortoiseGit.
- After the fixes and commit has been completed, check to see build passes without problems.
- And, continue until merge work is complete, fixes and commit the problems that have been discovered.

### Other than the source file
Check point.

- *. sln
  - Format Version
  - TargetFrameworkMoniker
- */...proj
  - TargetFrameworkVersion
  - ToolsVersion=
- *.config
  - targetFramework
- else
  - *.bat
  - readme.* (*.txt, *.md)

### Update file
- To regenerate the designer.cs or vb files of resource file by re-run the custom tool (Resgen.exe).
- Unnecessary possibilities : \<pages controlRenderingCompatibilityVersion="x" clientIDMode="x"/>
- Delete the reference to the WPFToolKit from WPF Sample project file and *.xaml file.
- Add the reference to the PCLFramework to Silverlight Sample project file.
- Add the descriptions of the how to build and execute to the readme.md file.

### Delete file
- Delete Portable Class Library *.dll file. And, append to "ignore list" in the .gitignore.
- Delete certificate of pfx format file. And, append description that to add the pfx for to build the project.
- Delete WinAzure_sample from "root" excluding "root_VS2013".

**Comment by daisukenishino** [comment] 2015-07-06 03:35
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Util/CustomMarshaler.cs#L295
XML comment has not been filled.

**Comment by daisukenishino** [comment] 2015-07-06 03:44
XML comment of DTTable.SavejqGridJson method has not been filled.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Dto/DTTable.cs#L409

**Comment by supragyan** [comment] 2015-07-06 07:12
Dear Nishino-San,
\>XML comment of CustomMarshaler.PrimitivetypeFromString method has not been filled.
\>It is not possible to use methods for the description of the parameters is not sufficient.
\>Please send as text without committing the modification for the following problems.

We modified this  xml comment as below:
/// <summary>
        /// To converts all string data to premitive Type by colType and cellString.
        /// </summary>
        /// <param name="colType">Column data type</param>
        /// <param name="cellString">Cell data</param>
        /// <returns></returns>
Is it ok or not?
Please confirm.

**Comment by supragyan** [comment] 2015-07-06 07:52
Dear Nishino-San,

\>XML comment of DTTable.SavejqGridJson method has not been filled.

We modified xml comment for SavejqGridJson method as below:

/// \<summary\>
/// SavejqGridJson method for converting datatable data to JQGrid data by passing total count,rows of current page.
        /// \</summary\>
        /// \<param name="data"\>DataTable data\</param\>
        /// \<param name="totalCount"\>Total count\</param\>
        /// \<param name="page"\>current page number\</param\>
        /// \<param name="rows"\>Rows count\</param\>
        /// \<returns\>returns JQGrid data\</returns\>
Is it ok or not?
Please confirm

**Comment by daisukenishino** [comment] 2015-07-06 09:54
Fixes for the following point is leaking.
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/files/tools/DGenTemplates/DaoTemplate.cs#L88
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/files/tools/DGenTemplates/DaoTemplate.vb#L86

Please refer to the following.
- https://github.com/OpenTouryoProject/OpenTouryo/issues/57#issuecomment-85957619

**Comment by kishoreandukuri** [comment] 2015-07-06 10:13
Dear Nishino-san,

Please let me know whats is the leak here.

Thanks and Regards

**Comment by daisukenishino** [comment] 2015-07-06 10:20
Do not worry about because my confirmation leaking also.

```C#
(((DamSqlSvr)this.GetDam()).DamIDbCommand).CommandTimeout = this._commandTimeout;
```
↓　↓　↓
```C#
(((IDbCommand)this.GetDam()).DamSqlCommand).CommandTimeout = this._commandTimeout;
```

**Comment by kishoreandukuri** [comment] 2015-07-06 10:37
Dear Nishino-san,

DamSqlSvr is the db class here we cannot use IDbCommand.

we need to develop generalised class for db classes

**Comment by daisukenishino** [comment] 2015-07-06 11:14
I think that is possible if you add DamIDbCommand properties as a pure virtual function to BaseDam.

In the case of abstract, impossible ?
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Db/BaseDam.cs#L177

**Comment by daisukenishino** [comment] 2015-07-06 11:20
Targetframework of ASP.NET had been hope the .NET ver3.5 but had been changed to the .NET ver4.0. However, the requested processing of jQGrid + JSON.NET seems to be the need .NET ver4.0.

There was a contradiction to the my request.

**Comment by daisukenishino** [comment] 2015-07-06 11:47
(No.5)
I want to provide the following changes to VB version.
- Sample code of text change event on testScreen2.aspx ( + app.config).
- jQGrid + JSON.NET (However, to provide against root_VS2010 because .NET 4.0 is required.)

**Comment by daisukenishino** [comment] 2015-07-06 12:08
Please describe in more detail.
- /// \<param name="totalCount"\>Total count\</param\>  
Total : What Total ?
- /// \<param name="rows"\>Rows count\</param\>  
Row: What Row ?

**Comment by daisukenishino** [comment] 2015-07-07 02:44
https://github.com/OpenTouryoProject/OpenTouryo/issues/104#issuecomment-118750864
https://github.com/OpenTouryoProject/OpenTouryo/issues/104#issuecomment-118762125
We have confirmed the above. 
Because I think good it, I will copy and paste it.

**Comment by daisukenishino** [comment] 2015-07-16 03:48
# No.5
Commit unnecessary files.
 (or, it have forgotten to delete from git repository.)

## Issue description
Delete from git repository.
- \root\programs\C#\Frameworks\Infrastructure\Framework\AsyncProcessingService

### Status
Working

**Comment by daisukenishino** [comment] 2015-07-16 06:48
# No.5
There is a possibility of bugs.

## Issue description
### DTTables
To the next line in the following lines
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Dto/DTTables.cs#L481

Do not need the following Step ?
```C#
row[colIndex] = primitiveData;
```
### Status
Now, during the confirmation.

**Comment by supragyan** [comment] 2015-07-16 07:57
@Nishino,
\>\>Do not need the following Step ?

\>\>row[colIndex] = primitiveData;

Yes this step is needed.
We did committed earlier for SaveJSON, LoadJSon, Save, Load method.
But now it seems like this step is not present for Load method in https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Dto/DTTables.cs#L481,

Do we need to commit again in https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Dto/DTTables.cs

Please confirm.

**Comment by daisukenishino** [comment] 2015-07-17 00:10
@supragyan

Please support by quickly verification.
In addition, tests should be carried out enough.

The contents of the verification and test are carried out as follows.

- Create a Datatable(1).
- Save as text using the DTTables.save method.
- Restored as Datatable(2) using DTTables.Load method from the text.
- Please confirm that the save and load processing  is appropriate  
by compare the contents of Datatable(1) and Datatable(2).

**Comment by daisukenishino** [comment] 2015-07-17 01:58
# No.7
There is a possibility of issue.

## Issue description
### DTTables
#### (1)
Commented out has been left for testing.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Infrastructure/Public/Dto/DTTables.cs#L58

```C#
//[System.Diagnostics.DebuggerStepThrough]
```

#### (2)
Save and Load method of DTTables in the PortableClassLibrary project has not been applied refactoring measures.
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/PortableClassLibrary/PCLPublic/Dto/DTTables.cs#L184
- https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/PortableClassLibrary/PCLPublic/Dto/DTTables.cs#L335

### Status
Now, during the confirmation.

**Comment by supragyan** [comment] 2015-07-17 09:48
@Nishino 

We will complete it by today.

Regards,

**Comment by supragyan** [comment] 2015-07-17 14:54
@Nishino,
\>Please support by quickly verification.
\>In addition, tests should be carried out enough.

We have tested as per your suggestion.
There is no problem.

Regards

**Comment by SandeepNayak077** [comment] 2015-07-21 04:19
@daisukenishino 

\>> In the current setting, SQL will be output to the build output. If not needed, I want to cancel the CopyToOutputDirectory setting.

- Please cancel the CopyToOutputDirectory setting. There is no need to copy SQL files in the build output. 
- Because, SQL files are embedded in the Business.dll project, and it is used by used by Infrastructure.Business.AsyncProcessingService.

**Comment by supragyan** [comment] 2015-07-23 08:13
@daisukenishino 
We have completed jQGrid + JSON.NET for vb version.

\>\>Targetframework of ASP.NET had been hope the .NET ver3.5 but had been changed to the .NET ver4.0. However, the requested processing of jQGrid + JSON.NET seems to be the need .NET ver4.0.

but after tested we confirmed Targetframework of ASP.NET needs v4.0 for jQGrid + JSON.NET 

\>\>There was a contradiction to the my request.

Shall we change version 3.5 to 4.0 and commit or do we need to commit in OpenTouryoProject/OpenTouryoTemplates.

Please confirm

**Comment by daisukenishino** [comment] 2015-07-23 10:27
@supragyan

Thank you for research.

"/OpenTouryoProject/OpenTouryo/" is already reverted.
Changes are merged into the "/OpenTouryoProject/OpenTouryoTemplates/".

According to the following Issue,
please merge this change to the VB version of the "/OpenTouryoProject/OpenTouryoTemplates/".
https://github.com/OpenTouryoProject/OpenTouryo/issues/105

**Comment by supragyan** [comment] 2015-07-23 13:00
@daisukenishino 

We have folked from OpenTouryoProject/OpenTouryoTemplate to SymphonyTeleca/OpenTouryoTemplate.

Please create nishino branch in SymphonyTeleca/OpenTouryoTemplate to create pull request for JQGrid+JSON in vb.net

Regards,

**Comment by supragyan** [comment] 2015-07-31 10:54
@daisukenishino ,

\>AsyncSvc_sample solution could not be build.
\>AsyncSvc_sample.csproj
\>•\root\programs\C#\Samples\AsyncSvc_sample\AsyncSvc_sample\AsyncSvc_sample.csproj
\>contains a reference of AsyncProcessingService.dll
\>•\root\programs\C#\Frameworks\Infrastructure\Framework\AsyncProcessingService\AsyncProcessingService\bin\Debug\AsyncProcessingService.dll

Yes, AsyncSvc_Sample contains AsyncProcessingService.dll earlier.

\>How do you generated the AsyncProcessingService.dll ?
We have created AsyncProcessingService class library in https://github.com/SymphonyTeleca/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/AsyncProcessingService.
It contains AsyncProcessingParameterValue.cs and AsyncProcessingServiceReturnValue.cs,LayerB,LayerC
After build this class library we used this dll in AsyncSvc_Sample project.

\> Does this have been described in the procedure document ?
No,It has not described in Procedure document.

**Comment by daisukenishino2** [comment] 2015-08-02 05:28
@supragyan

>Shall we commit AsyncProcessingService.dll ?

Do not commit the DLL.

We will check the specifications of AsyncSvc_sample again.

- It consists of two project.
  - The first project is only put the record of the task, and to see the results.
  - The second project is to implement the B layer and the D layer that will be called from the asynchronous processing service.

- Layer B and D layers for accessing the control table to use the components in https://github.com/SymphonyTeleca/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/AsyncProcessingService. Therefore, D layer for access to the management table in AsyncSvc_sample will not be created.

- It'll explain how to end and how to update the progress rate in this.
  - Successful completion.
  - Abnormal termination.
    - How to throw an exception if abnormal termination.
    - How to throw an exception if you want to retry.  
And, the point of start processing of the case that resume from the middle of the processing in retry

**Comment by supragyan** [comment] 2015-08-03 07:26
@daisukenishino 

\>it consists of two project.
\>The first project is only put the record of the task, and to see the results.
Yes in https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/AsyncSvc_sample/TestAsyncSvc_Sample 
it contains only insert task that will be inserted record to table.

\>The second project is to implement the B layer and the D layer that will be called from the asynchronous processing service.
In https://github.com/OpenTouryoProject/OpenTouryo/tree/develop/root/programs/C%23/Samples/AsyncSvc_sample/AsyncSvc_sample project,
it contains 
   i. implementation of LayerB and LayerD
   ii. B and D layers accessing  the table parameters by using https://github.com/SymphonyTeleca/OpenTouryo/tree/develop/root/programs/C%23/Frameworks/Infrastructure/Framework/AsyncProcessingService..

As per earlier specification,we implemented  only register task in TestAsyncSvc_Sample project.

\>It'll explain how to end and how to update the progress rate in this.
\>Successful completion.
\>Abnormal termination.
\>How to throw an exception if abnormal termination.
\>How to throw an exception if you want to retry.
\>And, the point of start processing of the case that resume from the middle of the processing at retry.
Do we need to implement Update task in AsyncSvc_Sample project?
Please confirm?

**Comment by daisukenishino** [comment] 2015-08-04 00:26
@supragyan 

>it contains only insert task that will be inserted record to table.

OK.

>As per earlier specification,we implemented only register task in TestAsyncSvc_Sample project.

OK.

>Do we need to implement Update task in AsyncSvc_Sample project?

Please implement the process of updating the progress rate.
Please fill out as a comment a description of the retry processing.

```C#
// (1) First, check the progress rate, if progress rate is greater than or equal to 0%, and resume the process from there.
・・・
// (2) You will update the progress rate.
// (3) If the retry possible exception occurs, please throw the BusinessapplicationException.
```

**Comment by supragyan** [comment] 2015-08-13 05:55
@daisukenishino 

\>\>Layer B and D layers for accessing the control table to use the components in　Infrastructure/Framework/AsyncProcessingService. 

We must use layerB and layerD components from Infrastructure/Busines/AsyncProcessingService.
because Infrastructure/Framework/AsyncProcessingService raises circular reference exception as we discussed earlier with the team.

\>Therefore, D layer for access to the management table in AsyncSvc_sample will not be created.

We must remove LayerD from AsyncSvc_Sample.
LayerB in AsyncSvc_Sample must perform following functionalties:
- Successful completion.
- Abnormal termination.
     - How to throw an exception if abnormal termination.
     - How to throw an exception if you want to retry.
     - And, the point of start processing of the case that resume from the middle of the processing at retry.

Shall we include Serialization and Deserialization functionalities in LayerB of AsyncSvc_Sample?

Please confirm our understanding.

**Comment by daisukenishino2** [comment] 2015-08-13 07:53
@supragyan 

>because Infrastructure/Framework/AsyncProcessingService raises circular reference exception as we discussed earlier with the team.

It has error about my description. However, In the first place, I think the "Infrastructure/Framework/AsyncProcessingService" should be deleted. 

>Shall we include Serialization and Deserialization functionalities in LayerB of AsyncSvc_Sample?

Of course.

The implementation standards of asynchronous task must be implemented in the sample.
And implementation standards is also described in the procedure manual.

**Closed** 2015-08-25 06:04 UTC
Labels: enhancement
